"""Generate vbaProject.bin templates using WPS COM automation.

This script creates base VBA project files that can be used for deployment
without requiring pywin32 on subsequent runs.
"""

import os
import sys
import zipfile
import shutil
import io

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def generate_excel_vba_template(output_dir: str) -> bool:
    """Generate Excel vbaProject.bin using COM automation."""
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 not available. Please install: pip install pywin32")
        return False

    try:
        # Try to connect to existing WPS instance or start a new one
        try:
            et = win32com.client.GetActiveObject('Ket.Application')
        except:
            et = win32com.client.Dispatch('Ket.Application')

        et.Visible = False

        # Enable VBA project access (may be required for some WPS versions)
        try:
            et.VBE.VBProjects  # Test access
        except:
            print("WARNING: VBA project access may be limited")

        # Create a new workbook
        wb = et.Workbooks.Add()

        # Add VBA code to ThisWorkbook
        try:
            vb_project = wb.VBProject
            print(f"  VBProject found: {vb_project.Name}")

            try:
                vb_component = vb_project.VBComponents.Item('ThisWorkbook')
                vb_component.CodeModule.AddLines('''
Private Sub Workbook_Open()
    ' Auto-execute on workbook open
End Sub
''')
            except:
                vb_component = vb_project.VBComponents.Add(1)
                vb_component.CodeModule.AddLines('''
Private Sub Workbook_Open()
    ' Auto-execute on workbook open
End Sub
''')

            # Add a standard module with sample code
            vb_component = vb_project.VBComponents.Add(1)
            vb_component.Name = 'WpsScriptManager'
            vb_component.CodeModule.AddLines('''
Sub ScriptManager_Main()
    ' Auto-generated by WPS Script Manager
End Sub
''')
        except Exception as e:
            print(f"  WARNING: VBA project error: {e}")

        # Save as .xlam to get the vbaProject.bin
        temp_path = os.path.join(output_dir, 'temp_excel.xlam')
        wb.SaveAs(temp_path, 52)  # 52 = xlOpenXMLAddIn
        wb.Close(False)
        et.Quit()

        # Extract vbaProject.bin from the .xlam file
        with zipfile.ZipFile(temp_path, 'r') as zf:
            if 'xl/vbaProject.bin' in zf.namelist():
                vba_bin = zf.read('xl/vbaProject.bin')
                output_path = os.path.join(output_dir, 'vbaProject_excel.bin')
                with open(output_path, 'wb') as f:
                    f.write(vba_bin)
                print(f"OK: Excel vbaProject.bin saved to: {output_path}")
                print(f"   Size: {len(vba_bin)} bytes")
                return True
            else:
                print("ERROR: vbaProject.bin not found in .xlam file")
                return False

    except Exception as e:
        print(f"ERROR: Error generating Excel VBA template: {e}")
        return False


def generate_word_vba_template(output_dir: str) -> bool:
    """Generate Word vbaProject.bin using COM automation."""
    try:
        import win32com.client
    except ImportError:
        print("ERROR: pywin32 not available. Please install: pip install pywin32")
        return False

    try:
        # Try to connect to existing WPS instance or start a new one
        try:
            word = win32com.client.GetActiveObject('Kwps.Application')
        except:
            word = win32com.client.Dispatch('Kwps.Application')

        word.Visible = False

        # Create a new document
        doc = word.Documents.Add()

        # Add VBA code to ThisDocument
        try:
            vb_project = doc.VBProject
            print(f"  VBProject found: {vb_project.Name}")

            try:
                vb_component = vb_project.VBComponents.Item('ThisDocument')
                vb_component.CodeModule.AddLines('''
Private Sub Document_Open()
    ' Auto-execute on document open
End Sub
''')
            except:
                vb_component = vb_project.VBComponents.Add(1)
                vb_component.CodeModule.AddLines('''
Private Sub Document_Open()
    ' Auto-execute on document open
End Sub
''')

            # Add a standard module with sample code
            vb_component = vb_project.VBComponents.Add(1)
            vb_component.Name = 'WpsScriptManager'
            vb_component.CodeModule.AddLines('''
Sub ScriptManager_Main()
    ' Auto-generated by WPS Script Manager
End Sub
''')
        except Exception as e:
            print(f"  WARNING: VBA project error: {e}")

        # Save as .dotm to get the vbaProject.bin
        temp_path = os.path.join(output_dir, 'temp_word.dotm')
        doc.SaveAs(temp_path, 5)  # 5 = wdFormatXMLDocumentMacro
        doc.Close(False)
        word.Quit()

        # Extract vbaProject.bin from the .dotm file
        with zipfile.ZipFile(temp_path, 'r') as zf:
            if 'word/vbaProject.bin' in zf.namelist():
                vba_bin = zf.read('word/vbaProject.bin')
                output_path = os.path.join(output_dir, 'vbaProject_word.bin')
                with open(output_path, 'wb') as f:
                    f.write(vba_bin)
                print(f"OK: Word vbaProject.bin saved to: {output_path}")
                print(f"   Size: {len(vba_bin)} bytes")
                return True
            else:
                print("ERROR: vbaProject.bin not found in .dotm file")
                return False

    except Exception as e:
        print(f"ERROR: Error generating Word VBA template: {e}")
        return False


if __name__ == '__main__':
    output_dir = r'D:\ScriptNexus\templates'

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print("=" * 60)
    print("Generate VBA Project Templates")
    print("=" * 60)
    print()

    excel_success = generate_excel_vba_template(output_dir)
    print()
    word_success = generate_word_vba_template(output_dir)

    print()
    print("=" * 60)
    if excel_success and word_success:
        print("SUCCESS: All VBA project templates generated!")
    elif excel_success or word_success:
        print("WARNING: Some templates generated (check errors above)")
    else:
        print("ERROR: Failed to generate VBA project templates")
    print("=" * 60)
