#!/usr/bin/env python
"""Minimal COM deployment test - tests basic VBA code injection.

This tests the simplest possible case to isolate the problem.
"""

import sys
import os
import tempfile
import win32com.client

# Fix Windows console encoding
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

print("=" * 70)
print("Minimal COM Deployment Test")
print("=" * 70)
print()

# Test 1: Word with simplest possible code
print("[Test 1] Word - Simplest VBA code...")
try:
    word = win32com.client.Dispatch('Kwps.Application')
    word.Visible = False
    doc = word.Documents.Add()
    vb_project = doc.VBProject

    # Create a standard module
    new_module = vb_project.VBComponents.Add(1)
    new_module.Name = "SimplestTest"

    # Try the absolute simplest VBA code
    simplest = "Sub AutoExec()\nMsgBox \"Test\"\nEnd Sub"
    new_module.CodeModule.AddLines(simplest)
    print("  SUCCESS: Added simplest VBA code")

    # Save
    temp_file = os.path.join(tempfile.gettempdir(), "test_word_simple.dotm")
    doc.SaveAs(temp_file, 5)
    print(f"  Saved to: {temp_file}")

    doc.Close(False)
    word.Quit()
    print("  Word test PASSED")
except Exception as e:
    print(f"  FAILED: {e}")
    print(f"  Error code: 0x{abs(e.args[0]):08X}" if e.args else "No error code")

# Test 2: Word with our generated code structure
print("\n[Test 2] Word - Generated code structure...")
try:
    word = win32com.client.Dispatch('Kwps.Application')
    word.Visible = False
    doc = word.Documents.Add()
    vb_project = doc.VBProject

    # Create a standard module
    new_module = vb_project.VBComponents.Add(1)
    new_module.Name = "GeneratedCodeTest"

    # Try the exact structure we generate
    generated = """' Auto-generated by WPS Script Manager
Sub ScriptManager_Main()
    ' Test Button
    Call TestScript_Main
End Sub

Sub TestScript_Main()
    ' Test Button
    MsgBox "Hello"
End Sub
"""
    new_module.CodeModule.AddLines(generated)
    print("  SUCCESS: Added generated VBA code structure")

    # Save
    temp_file = os.path.join(tempfile.gettempdir(), "test_word_generated.dotm")
    doc.SaveAs(temp_file, 5)
    print(f"  Saved to: {temp_file}")

    doc.Close(False)
    word.Quit()
    print("  Generated code test PASSED")
except Exception as e:
    print(f"  FAILED: {e}")
    print(f"  Error code: 0x{abs(e.args[0]):08X}" if e.args else "No error code")

# Test 3: Excel
print("\n[Test 3] Excel - Simplest VBA code...")
try:
    et = win32com.client.Dispatch('Ket.Application')
    et.Visible = False
    wb = et.Workbooks.Add()
    vb_project = wb.VBProject

    # Create a standard module
    new_module = vb_project.VBComponents.Add(1)
    new_module.Name = "SimplestTest"

    # Simplest code
    simplest = "Sub Auto_Open()\nMsgBox \"Test\"\nEnd Sub"
    new_module.CodeModule.AddLines(simplest)
    print("  SUCCESS: Added simplest VBA code")

    # Save
    temp_file = os.path.join(tempfile.gettempdir(), "test_excel_simple.xlam")
    wb.SaveAs(temp_file, 52)
    print(f"  Saved to: {temp_file}")

    wb.Close(False)
    et.Quit()
    print("  Excel test PASSED")
except Exception as e:
    print(f"  FAILED: {e}")
    print(f"  Error code: 0x{abs(e.args[0]):08X}" if e.args else "No error code")

print("\n" + "=" * 70)
print("All tests completed.")
print("=" * 70)
